server:
  port: ${AUTH_SERVICE_PORT}

spring:
  config:
    import: "optional:file:./.env[.properties],optional:file:../.env[.properties],optional:file:../../.env[.properties]"
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${AUTH_DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  seed:
    admin-email: ${APP_SEED_ADMIN_EMAIL:admin@cinebook.com}
    admin-password: ${APP_SEED_ADMIN_PASSWORD:admin123}
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiry-ms: ${JWT_ACCESS_EXPIRY_MS}
    refresh-token-expiry-ms: ${JWT_REFRESH_EXPIRY_MS}
    issuer: cinebook-auth-service
  otp:
    expiry-minutes: 10
  rate-limit:
    max-attempts: 10
    window-minutes: 5
  # cors:
  #   allowed-origins: ${CORS_ALLOWED_ORIGINS}
  mail:
    from-name: CineBook
    from-address: ${MAIL_USERNAME}
    dev-mode: ${MAIL_DEV_MODE}


logging:
  level:
    com.cinebook.auth: INFO
