name: Build, Push to GHCR and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        service:
          - name: cinebook-frontend
            context: ./cinebook-frontend
          - name: admin-service
            context: ./admin-service
          - name: api-gateway
            context: ./api-gateway
          - name: auth-service
            context: ./auth-service
          - name: booking-service
            context: ./booking-service
          - name: catalog-service
            context: ./catalog-service
          - name: notification-service
            context: ./notification-service
          - name: payment-service
            context: ./payment-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase Repository Owner String
        id: repository_owner
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (Tags & Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repository_owner.outputs.owner }}/${{ matrix.service.name }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_BASE_URL=https://api-gateway.lemondesert-03dc2ff4.eastasia.azurecontainerapps.io

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ matrix.service.name }}
          resourceGroup: student-microservices-rg
          imageToDeploy: ghcr.io/${{ steps.repository_owner.outputs.owner }}/${{ matrix.service.name }}:latest
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
